name: scratch-mssql

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    hostname: scratch-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - mssql-db-vol:/var/opt/mssql

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools:latest
    restart: no
    command: "/opt/mssql-tools/bin/sqlcmd -S scratch-mssql -l 60 -U sa -P '${DB_PASSWORD}' -d master -i /tmp/mssql-init.sql"
    depends_on:
      - mssql
    volumes:
      - ./mssql-init.sql:/tmp/mssql-init.sql

networks:
  default:
    name: scratch-mssql-net

volumes:
  mssql-db-vol:
